[package]
name = "youtubby"
version = "0.1.0"
edition = "2021"
authors = ["fazibear"]
homepage = "https://youtubby.fazibear.me"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wry = "0.40.1"
tao = "0.28"
tray-icon = "0.14.2"
muda = "0.13.5"
global-hotkey = "0.5.4"
image = "0.25.1"
serde_json = "1.0.117"
serde = "1.0.203"
directories = "5.0.1"
reqwest = { version = "0.12.4", features = ["blocking"] }
url = "2.5.0"
md5 = "0.7.0"
serde_json_path = "0.6.7"
form_urlencoded = "1.2.1"
url_encoded_data = "0.6.1"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"
shell32-sys = "0.1.2"
